version: 2.1

jobs:
  test_python:
    docker:
      - image: circleci/python:3.5
    steps:
      - checkout
      - run:
          name: Install test dependencies
          command: pip install . pytest
      - run:
          name: "Run Pytest tests"
          command: pytest

  test_publish:
    docker:
      - image: circleci/python:3.5
    steps:
      - checkout
      - run: pip install twine
      - run: python setup.py sdist
      - run: twine upload --repository-url https://test.pypi.org/legacy/ dist/* -u ${TWINE_USERNAME} -p ${TWINE_PASSWORD}

  publish:
    docker:
      - image: circleci/python:3.5
    steps:
      - checkout
      - run: pip install twine
      - run: python setup.py sdist
      - run: twine upload dist/* -u ${TWINE_USERNAME} -p ${TWINE_PASSWORD}

workflows:
  version: 2
  test_and_publish:
    jobs:
      - test_python
      - publish:
          requires:
            - test_python
          filters:
            branches:
              only: master
